yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('django.contrib.auth.urls')),
]

yatube/posts/models.py
from django.db import models

from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название группы')
    slug = models.SlugField(unique=True, max_length=400,
                            verbose_name='Адресс группы')
    description = models.TextField(verbose_name='Описание группы')

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name='Текст поста')
    pub_date = models.DateTimeField(auto_now_add=True,
                                    verbose_name='Дата публикации')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(Group,
                              blank=True, null=True,
                              on_delete=models.SET_NULL,
                              related_name='posts',
                              verbose_name='Группа')

    def __str__(self):
        return self.text

    class Meta:
        ordering = ['-pub_date']

yatube/posts/forms.py
from django import forms
from django.contrib.auth import get_user_model

from .models import Post


User = get_user_model()


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')
        group = forms.ModelChoiceField(queryset=Post.objects.all(),
                                       required=False, to_field_name='group')
        widgets = {
            'text': forms.Textarea(),
        }

        labels = {
            'text': 'Текст поста',
            'group': 'Группа',
        }

yatube/posts/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from .models import Post, Group, User
from .forms import PostForm


POSTS_ON_PAGE = 10


def index(request):
    post_list = Post.objects.select_related('author').all()
    paginator = Paginator(post_list, POSTS_ON_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts_list = group.posts.all()
    paginator = Paginator(posts_list, POSTS_ON_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'posts': posts_list,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts_count = author.posts.count()
    title = f'Профиль пользователя {author}'

    paginator = Paginator(author.posts.all(), 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'author': author,
        'title': title,
        'posts_count': posts_count,
        'page_obj': page_obj,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    posts_count = Post.objects.all().count()
    context = {
        'post': post,
        'posts_count': posts_count,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None)
    title = 'Новый пост'
    if form.is_valid():
        form.instance.author = request.user
        form.save()
        return redirect('posts:profile', request.user.username)
    return render(request, 'posts/post_create.html', context={'form': form,
                                                              'title': title})


@login_required
def post_edit(request, post_id):
    is_form_edit = True
    post = get_object_or_404(Post, id=post_id)
    title = 'Редактирование поста'
    if post.author != request.user:
        return redirect('posts:post_detail', post_id)

    form = PostForm(request.POST or None, instance=post)
    if form.is_valid():
        post = form.save()
        return redirect('posts:post_detail', post_id)

    return render(request, 'posts/post_create.html',
                  context={'form': form,
                           'is_form_edit': is_form_edit,
                           'post': post,
                           'title': title})

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block content_title %}Записи сообщества {{ group }}{% endblock %}
      {% block content %}
      <div class="container py-5">
        <h1>{{ group }}</h1>
        <p>{{ group.description }}</p>
        <article>
          {% for post in page_obj %}  
            <ul>
              <li>
                Автор:
                <a href="{% url 'posts:profile' post.author %}">{{ post.author }}</a>
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
            </ul>      
            <p>
              {{ post.text }}
            </p>
            <a href="">все записи группы</a>
            {% if not forloop.last %}<hr>{% endif %}
          {% endfor %}
          {% include 'posts/includes/paginator.html' %}     
        </article>
      </div> 
      {% endblock %}   

yatube/templates/posts/index.html
  {% extends 'base.html' %}
      {% block content %}
      <div class="container py-5">     
        <h1>Последние обновления на сайте</h1>
        <article>
          {% for post in page_obj %}
            <ul>
              <li>
                Автор:
                <a href="{% url 'posts:profile' post.author %}">{{ post.author }}</a>
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
            </ul>
            <p>
              {{ post.text }}
            </p>
            <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a></br>
            {% if post.group %}
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            {% endif %}
            {% if not forloop.last %}<hr>{% endif %}
          {% endfor %}
          {% include 'posts/includes/paginator.html' %}
        </article>
        <hr>
      </div>  
      {% endblock %}  

yatube/templates/posts/post_create.html
{% extends "base.html" %}
{% block content_title %}{{ title }}{% endblock %}
{% block content %}
{% load user_filters %}
<div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header d-flex justify-content-center">
            {% if is_form_edit %}
              Редактирование
            {% else %}
              Новый пост
            {% endif %}
          </div>
          <div class="card-body">
            {% if is_form_edit %}
              <form action="{% url 'posts:post_edit' post.id %}" method="post">
            {% else %}
              <form action="{% url 'posts:post_create' %}" method="post">
            {% endif %}
            {% for key, value in form.errors.items %}
              <div class="alert alert-danger" role="alert">
               {{ value|escape}}
              </div>
            {% endfor %}
            {% csrf_token %}
              {% for field in form %}
              <div class="form-group row my-1 p-2 justify-content-center">
              {{ field|addclass:'form-control' }}
              {{ field.label }}
              </div>
              {% endfor %}
            <div class="d-flex justify-content-center">  
              <button type="submit" class="btn btn-primary" >
                {% if is_form_edit %}
                  Сохранить изменения
                {% else %}
                  Создать пост
                {% endif %}
              </button>
            </div>
            </form>
          </div> 
        </div> 
      </div> 
    </div> 
</div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block content_title %}Пост {{ post.text|truncatechars:30 }}{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ post.pub_date|date:"d E Y" }} 
          </li >
          {% if post.group %}  
          <li class="list-group-item"> 
            <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы</a>
          </li>
            {% endif %}
          <li class="list-group-item">
            Автор: {{ post.author.get_full_name }}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора:  <span >{{ posts_count }}</span>
          </li>
          <li class="list-group-item">
            <a href="../profile/<username>">
              Все посты пользователя
            </a>
          </li>
        </ul>
      </aside>
      <article class="col-12 col-md-9">
        <p>
          {{ post.text }}
        </p>
      </article>
        <div class="my-2 d-flex justify-content-center">  
            <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}" role="button">
              Редактировать
            </a>
        </div>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block content_title %}{{ title }}{% endblock %}
{% block content %}
      <div class="container py-5">        
        <h1>Все посты пользователя {{ author }}</h1>
        <h3>Всего постов: {{ posts_count }} </h3>   
        <article>
            {% for post in page_obj %}
            <ul>
              <li>
                Автор: {{ author }}
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
            </ul>
            <p>
              {{ post.text }}
            </p>
            {% if post.group %}   
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            {% endif %}
            {% if not forloop.last %}<hr>{% endif %}
          {% endfor %}
          {% include 'posts/includes/paginator.html' %}
        </article>        
      </div>
{% endblock%}